name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build app
        run: ./gradlew assembleRelease -Pinclude-telemetry -Penable-updater

      - name: Upload APK
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk

      - name: Upload mapping
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release

      # Sign APK and create release for tags

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -e
          mv app/build/outputs/apk/release/app-universal-release-unsigned-signed.apk tadami-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum tadami-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV
          mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk tadami-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum tadami-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV
          mv app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk tadami-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum tadami-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV
          mv app/build/outputs/apk/release/app-x86-release-unsigned-signed.apk tadami-x86-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum tadami-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV
          mv app/build/outputs/apk/release/app-x86_64-release-unsigned-signed.apk tadami-x86_64-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum tadami-x86_64-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Tadami ${{ env.VERSION_TAG }}
          body: |
            ---
            ### Checksums
            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86 | ${{ env.APK_X86_SHA }} |
            | x86_64 | ${{ env.APK_X86_64_SHA }} |
            ## If you are unsure which version to choose then go with tadami-${{ env.VERSION_TAG }}.apk
          files: |
            tadami-${{ env.VERSION_TAG }}.apk
            tadami-arm64-v8a-${{ env.VERSION_TAG }}.apk
            tadami-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            tadami-x86-${{ env.VERSION_TAG }}.apk
            tadami-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
